added MediaQuery, useMediaQuery
Warckut/react-responsive pull request #1
Opened 2024-07-08 08:07 UTC by Warckut

2024-07-08 08:12 UTC, Warckut commented
@tvivls

2024-07-08 10:55 UTC, tvivls requested changes
1. сделай поддержку реакта от 16.8.0

2024-07-08 10:55 UTC, tvivls commented on rollup.config.js
> +//NEW
коммент ни о чем не говорит
он тебе тут точно нужен?

2024-07-08 10:55 UTC, tvivls commented on rollup.config.js
> +const packageJson = require('./package.json')
`require`, но выше пишешь import, почему?

2024-07-08 10:55 UTC, tvivls commented on rollup.config.js
> +      // NEW
убирай

2024-07-08 10:55 UTC, tvivls commented on src/components/MediaQuery/MediaQuery.tsx
> +import React, { useMemo } from 'react';
убери React
лучше не тянуть всю библиотеку за собой, а импортировать из нее только нужное

2024-07-08 10:55 UTC, tvivls commented on src/components/MediaQuery/MediaQuery.tsx
> +function resolution(v: Resolution) {
опять эти `v`))
пиши нормальные названия для аргументов, констант, ...

2024-07-08 10:55 UTC, tvivls commented on src/components/MediaQuery/MediaQuery.tsx
> +function resolution(v: Resolution) {
название у функций должно отражать **действие**

2024-07-08 10:55 UTC, tvivls commented on src/components/MediaQuery/MediaQuery.tsx
> +    ...(maxHeight ? [`(max-height: ${maxHeight}px)`] : []),
давай сокращать

2024-07-08 10:55 UTC, tvivls commented on src/components/MediaQuery/types/index.ts
> +  children: React.ReactNode | ((matches: boolean) => React.ReactNode);
```suggestion
  children: ReactNode | ((matches: boolean) => ReactNode);
```

2024-07-08 10:55 UTC, tvivls commented on src/components/MediaQuery/types/index.ts
> +export type Resolution = `${number}${'dppx' | 'dpi' | 'dpcm'}` | number;
обычно для типов дописываем Type в названии (`ResolutionType`).
некоторые аналогично делают для интерфейсов (`IMediaQueryParams`), но не всегда и не везде.

2024-07-08 10:55 UTC, tvivls commented on src/hooks/useMediaQuery/useMediaQuery.ts
для проверки media query можешь использовать свой же хук

2024-07-08 10:55 UTC, tvivls commented on src/hooks/useMediaQuery/useMediaQuery.ts
> +    setMatch(ref.current.matches);
используй `target`

2024-07-08 11:23 UTC, tvivls commented
Eslint еще добавь (без prettier)

2024-07-10 15:49 UTC, Warckut commented
@tvivls, исправил

2024-07-12 17:12 UTC, tvivls requested changes
давай добавим поддержку SSR

2024-07-12 17:12 UTC, tvivls commented on src/components/MediaQuery/MediaQuery.tsx
> +  return <Fragment>{children}</Fragment>;
можно просто <></>

2024-07-12 17:12 UTC, tvivls commented on src/components/MediaQuery/MediaQuery.tsx
> +const getQuery = ({
можно еще сократить)

2024-07-12 17:12 UTC, tvivls commented on src/components/MediaQuery/MediaQuery.tsx
> +function MediaQuery({ children, ...mediaQuery }: MediaQueryProps) {
попробуй добавить проверку, чтобы обязательно был прокинут хотя бы один проп

2024-07-12 17:12 UTC, tvivls commented on package.json
> +    "react": "^16.8.0",
вынеси react в dependencies
все, из чего импортируешь в `src/`, должно быть в dependencies

2024-07-15 09:12 UTC, Warckut commented on package.json
> +    "react": "^16.8.0",
я вынес react из dev dependencies, но зачем react нужен в dependencies, если в peerDependecies, уже указаны необходимые версии, которые должны быть установлены на проекте, использующем мой package? На самом деле я уже пробывал  так сделать и словил ошибку. Одна из возможных причин ошибки - это использование нескольких копий react в одном приложении

2024-07-15 09:13 UTC, Warckut commented
@tvivls, исправил

2024-07-16 18:59 UTC, tvivls commented on src/components/MediaQuery/MediaQuery.tsx
> +const getQuery = (params: MediaQueryParams) => {
👍🏻
только везде пишешь function, а тут const () => {}

2024-07-16 18:59 UTC, tvivls commented on src/hooks/useMediaQuery.ts
> +  const [match, setMatch] = useState<boolean>(false);
<boolean> тип - излишне
тк ты тут передаешь initialValue и у тебя не может быть других значений (чисел, строк или null, undefined, к примеру)

2024-07-16 18:59 UTC, tvivls commented on src/components/MediaQuery/types/index.ts
> +  [K in keyof T]: Required<Pick<T, K>>;
по-моему оно не работает ?

2024-07-22 16:47 UTC, Warckut commented
@tvivls, исправил

2024-07-24 09:10 UTC, tvivls approved these changes

2024-07-24 19:17 UTC, merged